server:
  port: 8080

jwt:
  secret: 8294cdf937a12aade7ae45c0f3ddec08f59a0e496f0a6532b00a67efb4c5e38d6ac3f631cc8f856fb66a6f95d82f3bf47522b999702cf086babb66aa4b689baf
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/




  h2:
    console:
      enabled: true

  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/art_gallery?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

#      jdbc-url: jdbc:mysql://localhost:3306/art_gallery?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: root
      password: Fngml2tp^^

      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 180000

  # 파일 용량
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  #    prefix: file:src/main/resources/templates

  jpa:
    #    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
      use_sql_comments: true

# swaggerdoc
springdoc:
  #  packages-to-scan: com.encore.playground
  swagger-ui:
    path: /apiui.html
    tags-sorter: method
    operations-sorter: method
  api-docs:
    groups:
      enabled: true
    path: /api-docs/json
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  paths-to-match: /api/**

logging:
  file:
    path: /Users/real/Desktop/file/image/

  level:
    com.zaxxer.hikari.pool.HikariPool: debug


